[package]
name = "runtime-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
capability-graph = { path = "../capability-graph" }
execution-stream = { path = "../execution-stream" }
graph-core = { path = "../core" }
workflow-graph = { path = "../workflow-graph" }
workflow-recovery = { path = "../workflow-recovery" }

[lints]
workspace = true
